---
abstract: 'A Markdown formatter for Kwiki.'
author:
  - 'Copyright 2006 by Kang-min Liu <gugod@gugod.org>.'
build_requires:
  Test::Base: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.027, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kwiki-Markdown
provides:
  Kwiki::Markdown:
    file: lib/Kwiki/Markdown.pm
    version: '0.01'
requires:
  Kwiki: '0'
  Text::Markdown: '0'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
